### ISSUE TITLE
wrong gravity compensator?

### ISSUE THREAD

**Issue by jacknlliu** [KITrobotics/force_torque_sensor#20]
https://github.com/KITrobotics/force_torque_sensor/blob/1065d1405a0c415fd3230d61d3e2600f1b093ef6/src/force_torque_sensor_handle.cpp#L558

`transformed_data` uses the frame `transform_frame_`, and this will cause the `gravity_compensator_` can't [transform the CoG](https://github.com/KITrobotics/iirob_filters/blob/kinetic-devel/include/iirob_filters/gravity_compensation.h#L175) correctly!

**Comment by destogl** [comment]
I do not really understand the error...

**Comment by jacknlliu** [comment]
It's been a long time, but I'll give you more explanation.

**Comment by destogl** [comment]
Only if its important to you...
